[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"


[project]
name = "komickers"
version = "0.4.0"
description = "Download your comics automatically, using your terminal alone"
readme = "README.md"
authors = [{ name = "Arshia Shaygan", email = "arshiashaygan07@gmail.com" }]
requires-python = ">=3.11"
dependencies = [
    "beautifulsoup4>=4.15.0",
    "httplib2>=0.31.0",
    "httpx>=0.28.1",
    "httpx-retries>=0.6.0",
    "platformdirs>=4.11.7",
    "tomlkit>=0.15.1",
]

[project.optional-dependencies]
dev = ["pytest >= 7.0.0", "ruff >= 0.16.5", "mypy >= 2.3.1"]

google = [
    "google-api-core>=2.26.0",
    "google-api-python-client>=2.184.0",
    "google-auth-httplib2>=0.2.0",
    "google-auth-oauthlib>=1.2.2",
]

all = ["komickers[dev,google]"]

[project.scripts]
komickers = "komickers.main:main"


[tool.setuptools.packages.find]
where = ["src"]

[tool.ruff]
line-length = 88

[tool.ruff.lint]
extend-ignore = ["EXE002"]

[tool.mypy]
disable_error_code = ["import-untyped"]

[[tool.mypy.overrides]]
module = ["google.*"]
ignore_missing_imports = true
